#!/bin/bash

# who is my hard driver?
harddrive=$(mount | grep " / " | awk '{print $1}' | sed 's/\/dev\///g' | tr -d '[:digit:]')

lsblk | grep part | awk '{print $1,$7}' > /run/user/$(id -u)/partitions

sed '/'${harddrive}'/d' -i /run/user/$(id -u)/partitions

while read line
do mountp=$(echo "${line}" | awk '{print $2}')
[[ -z "${mountp}" ]] && parti=$(echo "${line}" | awk '{print $1}') || partid=sda1 
partid=$(echo "${parti}" | tr -dc '[:alnum:]')
puid=$(/sbin/blkid | grep ${partid} | sed 's/\ /\n/g' | grep ^UUID | cut -d \" -f 2)

[[ ! -d "/Volumes/${puid}" ]] && sudo mkdir -p "/Volumes/${puid}"

sudo mount "/dev/disk/by-uuid/${puid}" "/Volumes/${puid}"

done < /run/user/1000/partitions

