#!/bin/bash
#
# Backup by rsync on a specific hard drive.
# If you want to edit change the UUID from the partition
# where you want to back up and add below, to find the UUID
# run blkid as superuser.
# exemple of usage https://youtube.com/watch?v=dKkRgUIhn84
#

hardriveuuid=ffe7a7b8-daf8-45bd-86b0-d3a57acb99ea
device=$(blkid | grep ${hardriveuuid} | cut -d " " -f 1 | sed 's/\://' )
pointmount=$(mount | grep "${device}" | cut -d " " -f 3)

if [ -z ${device} ]
then echo "The device is not connected, aborting backup. Please make sure it is plugged and the cable is working."
exit 1
fi

if [ -z ${pointmount} ]
then echo "The hard drive is not mounted yet, mounting it now on /mnt"
	location=$(mount | grep "/mnt" | cut -d " " -f 1)
	if [ ! -z ${location} ]
		then echo "########## ERROR ############"
		echo "/mnt is mounted, but it is not your hard drive. umount it first"
		exit 1
		fi
	mount ${device} /mnt
	pointmount=/mnt
fi
rsync -havz --exclude=/mnt --exclude=/dev/ --exclude=/tmp --exclude=/proc --exclude=/sys / ${pointmount}
