#!/bin/bash
#
# Backup by rsync on a specific hard drive.
# If you want to edit change the UUID from the partition
# where you want to back up and add below, to find the UUID
# run blkid as superuser.
# exemple of usage https://youtube.com/watch?v=dKkRgUIhn84
#

if [ $UID != 0 ]
then echo "Best use this as root"
exit 1
fi

hardriveuuid=d6e2d2aa-feb2-4230-b222-d2411ff72769
device=$(blkid | grep ${hardriveuuid} | cut -d " " -f 1 | sed 's/\://' | sed -n 1p)
pointmount=$(mount | grep "${device}" | cut -d " " -f 3)

if [ -z ${device} ]
then wall << EOF
The device is not connected, aborting backup. Please make sure it is plugged and the cable is working.
EOF

exit 1
fi

if [ -z ${pointmount} ]
then wall << EOF
The hard drive is not mounted yet, mounting it now on /mnt
EOF

	location=$(mount | grep "/mnt" | cut -d " " -f 1)
	if [ ! -z ${location} ]
		then wall << EOF
		 ########## ERROR ############
		/mnt is mounted, but it is not your hard drive. umount it first
EOF

		exit 1
	fi
	mount ${device} /mnt
	pointmount=/mnt
fi

wall << EOF
Backup has started
EOF

rsync -havz --delete --exclude={/media/*,/mnt/*,/dev/*,/tmp/*,/proc/*,/sys/*,/home/mauricio/.local/Trash/*,/home/mauricio/.cache/*} / ${pointmount}
df -h ${pointmount}
umount ${device}

wall << EOF
Backup complete
EOF

