#!/bin/bash
#
# Backup by rsync on a specific hard drive.
# If you want to edit change the UUID from the partition
# where you want to back up and add below, to find the UUID
# run blkid as superuser.
# exemple of usage https://youtube.com/watch?v=dKkRgUIhn84
#

if [ $UID != 0 ]
then echo "Best use this as root"
exit 1
fi

hardriveuuid=2ea8b5cd-95e3-42fb-a326-5e7d268fb581
device=$(blkid | grep ${hardriveuuid} | cut -d " " -f 1 | sed 's/\://' | sed -n 1p)
pointmount=$(mount | grep "${device}" | cut -d " " -f 3)

if [ -z ${device} ]
then wall << EOF
The device is not connected, aborting backup. Please make sure it is plugged and the cable is working.
EOF

exit 1
fi

if [ -z ${pointmount} ]
then wall << EOF
The hard drive is not mounted yet, mounting it now on /mnt
EOF

	location=$(mount | grep "/mnt" | cut -d " " -f 1)
	if [ ! -z ${location} ]
		then wall << EOF
		 ########## ERROR ############
		/mnt is mounted, but it is not your hard drive. umount it first
EOF

		exit 1
	fi
	mount ${device} /mnt
	pointmount=/mnt
fi
umount /recovery

wall << EOF
Backup has started
EOF

rsync -havz --delete --exclude=/media --exclude=/mnt --exclude=/dev/ --exclude=/tmp --exclude=/proc --exclude=/sys / ${pointmount}
mount /recovery
df -h /mnt
umount /mnt

wall << EOF
Backup complete
EOF

