#!/bin/bash
# Check the battery level of the laptop.
# it is useful for window managers like i3
# Copyleft (C) 2016 Mauricio Luis de Medeiros
# This script is under GPL2
# https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

sleep 60

#  This delay is to give it time for all the programs to load during boot time 
# and gksu won't bother me while other thing are loading. 
#  This is my case any way, you may remove it if you'd like


statusquo=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | awk '{print $2}')

while [ 1 ]
	do statusquo=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | awk '{print $2}')
	sleep 30
		if [ $statusquo = "discharging" ]
		then bl=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | cut -d ":" -f 2 | sed 's/ //g' | sed 's/%//g')
		echo "the battery is being monitored" > /tmp/.bat.lock
	
		if [ "$bl" -lt "5" ]
		then i3-nagbar -m "Going down in 30 seconds, battery level ${bl}%"
		sleep 30
		systemctl hibernate
		fi
			if [ "$bl" -lt "10" ]
			then i3-nagbar -m "Battery level ${bl}%"
			fi
				if [ "$bl" -lt "20" ]
				then i3-nagbar -t warning -m "Battery level ${bl}%"
				fi
		else if [ -f /tmp/.bat.lock ]
			then shutdown -c "Aborting Shutdown"
			rm /tmp/.bat.lock
			fi
		fi
	done
