#!/bin/bash
# Check the battery level of the laptop.
# it is useful for window managers like i3
# Copyright (C) 2016-2020 Mauricio Luis de Medeiros
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# License GPL v2
# https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

sleep 30
# This delay is to add time for all the programs load during boot time. (My case, you may remove it you like)

while [ 1 ]
	do statusquo=$(cat /sys/class/power_supply/BAT1/status | awk '{print $1}')
	sleep 30
		if [ $statusquo = "Discharging" ]
		then bl=$(cat /sys/class/power_supply/BAT1/capacity | awk '{print $1}')
		echo "The battery is being monitored ${bl}%" > /tmp/.bat.log
		if [ "$bl" -lt "5" ]
		then notify-send -h string:bgcolor:#990000 "Shutting down in 20 seconds, battery level ${bl}%"
		sleep 20
		systemctl hibernate
		fi
			if [ "$bl" -lt "10" ]
			then notify-send -h string:bgcolor:#C37306 "Battery level ${bl}%"
			fi
					if [ "$bl" -lt "20" ]
					then notify-send -h string:bgcolor:#50248D "Battery level ${bl}%"
					fi
		else if [ -f /tmp/.bat.lock ]
			then echo "Aborting hibernation, battery is being charged"
			notify-send "Aborting hibernation, battery is being charged"
			rm /tmp/.bat.lock
			fi
		fi
	done
