#!/bin/bash
# Check the battery level of the laptop.
# it is useful for window managers like i3
# License GPL v2
# https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

sleep 60

notify-send "You will be prompted for the password for the battery monitor"
sleep 5
if [ $UID != 0 ]
then echo "Run as root"
gksu $0
fi
statusquo=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | awk '{print $2}')
while [ 1 ]
	do statusquo=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | awk '{print $2}')
	sleep 30
		if [ $statusquo = "discharging" ]
		then bl=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | cut -d ":" -f 2 | sed 's/ //g' | sed 's/%//g')
		echo the battery is being monitored > /tmp/.bat.lock
	
			if [ "$bl" -lt "10" ]
			then notify-send "Battery level ${bl}%" -i battery
			fi
				if [ "$bl" -lt "6" ]
				then notify-send "Plug your charger or save the files. You have one minute before the computer shutdown. Battery level ${bl}%" -i error
				fi
					if [ "$bl" -lt "3" ]
					then shutdown -h 30
					notify-send "Shutting down in 30 seconds, battery level ${bl}%"
					fi
		else if [ -f /tmp/.bat.lock ]
			then shutdown -c "Aborting Shutdown"
			notify-send $statusquo -i battery
			rm /tmp/.bat.lock
			else echo "The battery is ${statusquo}"
			fi
		fi
	done
