#!/bin/bash
# Check a folder for mp4 files and play them, after playback confirm if it should be deleted or not.

echo "Where should I seach for mp4 videos? End the path with /"
read fold

for i in ${fold}*.mp4
do mpv "${i}"
echo "Devo apagar"
read apa
	case "$apa" in 
		y) echo "Apagando $i"
		rm -f "${i}"
		;;
		*) echo "Keepping ${i}"
		;;
	esac;
done
