#!/bin/bash
# This script will kill all the share apps running
# Dropbox, MegaSync and Teamviewer.
# Copyright (C) 2016 Mauricio Luis de Medeiros
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# License GPL v2
# https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

dbox=$(ps axo pid,cmd | grep dropbox | grep -v grep | awk '{print $1}')
for i in $dbox;
do kill -9 $i > /dev/null;
done

mgsyn=$(ps axo pid,cmd | grep megasync | grep -v grep | awk '{print $1}')
for x in $mgsyn;
do kill -9 $x > /dev/null;
done


tv=$(ps axo pid,cmd | grep TeamViewer.exe | grep -v grep | awk '{print $1}')

pergunta=$(zenity --question --text "Do you want to kill TeamViewer?" --ok-label="Sure" --cancel-label="No Way" > /dev/null 1>&2) 

[ $? -eq 0 ] || exit 1

for g in $tv;
do kill -9 $g > /dev/null;
done

find $HOME -iname "*.tvs" -exec rm -f "{}" \; > /dev/null 2>&1
notify-send -i display "All teamviewer recordings for $USER were deleted"
