#!/bin/bash
# Encrypt/Decrypt files using ssl implementation of aes-256-cbc encryption
# Copyright (C) 2016 Mauricio Luis de Medeiros
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# License GPL v2
# https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

entrada=$(zenity --file-selection --text "Select the file to encrypt.")
todo=$(zenity --list --text "What do you want to do?" --checklist --column "Select" --column "Action" Encrypt Encrypt Decrypt Decrypt)

if [ $todo = Encrypt ]
then openssl enc -aes-256-cbc -e -in "${entrada}" -out "${entrada}.enc"
else openssl enc -aes-256-cbc -d -in "${entrada}" -out "$(echo ${entrada} | sed 's/\.enc//')"
fi
