#!/bin/sh
# Baseado no script de pekman
# email: fervelinux@openboxmail.com
# Licença: BSD
# Adaptacao: Minha mesmo :)

a="$1"
clear

echo -e "\e[32;5;1m entre com o texto a ser exibido na imagem \e[m"
read texto

echo -e "\e[35;5;1m entre a altura do texto \e[m"
read altura

width=$(identify -format %w "${a}")
convert -background "#990000" -fill gray75 -gravity center -size ${width}x${altura} caption:"$texto" "${a}" +swap -gravity south -composite up.jpg;
