#!/bin/sh
#Créditos pekman
#email: fervelinux@openboxmail.com
#Licença: BSD
a="$1"
clear

echo -e "\e[32;5;1m entre com o texto a ser exibido na imagem \e[m"
texto=$(curl https://feed.podbean.com/shannonmorse/feed.xml | grep \<title\> | sed -n 3p | sed 's/<title>//g' | sed 's/<\/title>//g')

echo -e "\e[35;5;1m entre a altura do texto \e[m"
altura=200

width=$(identify -format %w in "${a}")
convert -background "#990000" -fill gray75 -gravity center -font Titillium-Web-Regular -size ${width}x${altura} caption:"$texto" "${a}" +swap -gravity south -composite up.jpg;
#  +swap -gravity south -composite 
