#!/bin/bash
#
#  /etc/lightdm/lightdm-gtk-greeter.conf
#
#


new=$(find /usr/share/backgrounds | shuf | sed -n 1p)
cat > /etc/lightdm/lightdm-gtk-greeter.conf <<EOF
[greeter]
background = ${new}
icon-theme-name = nuoveXT2
position = 23%,center 20%,center
EOF


