#!/bin/bash
# Create a avi file using xvid codec at 1500 bitrate, 29.97 fps and 720:480 resolution.
# which is compatible with my karaoke device.
# Copyright (C) 2016 Mauricio Luis de Medeiros
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# License GPL v2
# https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
cd  $(pwd)
echo $(pwd)
sleep 10
for i in *.mp4
do echo Analizing "$i"
mencoder "$i" -ovc xvid -vf scale=720:480,harddup -ofps 30000/1001 -xvidencopts pass=1:turbo:autoaspect -passlogfile "${i}.log" -nosound -o /dev/null 2>&1
echo Converting "$i"
mencoder "$i" -ovc xvid -vf scale=720:480,harddup -ofps 30000/1001 -xvidencopts bitrate=1500:autoaspect:pass=2 -passlogfile "${i}.log" -oac mp3lame -lameopts vbr=3 -o "$(echo $i | sed 's/\.mp4/\.avi/g')" > /dev/null 2>&1 
done
