#!/usr/bin/env python
import random
import subprocess

banner = [ "futureprototype", "joy", "lines", "moonlight", "spacefun" ]
chosenb = random.choice(banner)

subprocess.call("plymouth-set-default-theme -R %s" % chosenb, shell=True);

