#!/bin/bash
# Record my voice-overs sections using my scalertt focusrite USB device.
# Copyright (C) 2016 Mauricio Luis de Medeiros
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# License GPL v2
# https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
card=$(arecord -l | grep USB | cut -d : -f 1 | awk '{print $2}')
arecord -t wav -f S32_LE -r 48000 -c 2 -D hw:${card},0 --use-strftime ~/Programmes/BM-audio/BM-%d-%m-%Y-id-%s.wav & echo $! > /tmp/recorder.pid
