#!/bin/bash
card=$(arecord -l | grep USB | cut -d : -f 1 | awk '{print $2}')
arecord -t wav -f S32_LE -r 48000 -c 2 -D hw:${card},0 --use-strftime /home/mauricio/Programmes/BM-audio/BM-%d-%m-%Y-id-%s.wav & echo $! > /tmp/recorder.pid
