#!/bin/bash
[ $USER != root ] && echo "Please run as root" && exit 1

for x in $(dpkg --list | grep -i linux-image | awk '{ print $2}')
do
	kernel="linux-image-$(uname -r)"
	realtime="linux-image-rt-amd64"

	[ "${x}" = "${kernel}" ] && x="" && b="${kernel}"
	[ "${x}" = "${realtime}" ] && x="" && b="${realtime}"

[ -z "${x}" ] && echo "Cannot remove ${b} as it is in use, It's all good."

[ ! -z "${x}" ] &&  echo "removing ${x}" && apt --purge remove ${x}

done
