#!/bin/bash
# Simple script to convert files using HandBrake
# Copyright (C) 2016 Mauricio Luis de Medeiros
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# License GPL v2
# https://www.gnu.org/licenses/old-licenses/gpl-2.0.html


i="$(zenity --file-selection --text 'Select File')"
HandBrakeCLI -i "$i" -t 1 -c 1 -o "$i.m4v"  -f mp4 -4  --decomb="7:2:6:9:1:80" -w 624 -l 722 --custom-anamorphic  --modulus 2 --display-width 1280  --keep-display-aspect  -e x264 -q 22 --vfr  -a 1,1 -E faac,ffac3 -B 128,128 -6 dpl2,dpl2 -R Auto,Auto -D 0,0 --gain=0,0 --audio-copy-mask none --audio-fallback ffac3 -x bframes=0 --verbose=1
