#!/usr/local/bin/bash

# Check which is the default device speaker or headphones
status=$(sysctl hw.snd.default_unit | cut -d " " -f 2)

# Toggle between then and exit.
[[ ${status} == 0 ]] && sysctl hw.snd.default_unit=1 && exit
[[ ${status} == 1 ]] && sysctl hw.snd.default_unit=0 && exit


