#!/bin/bash
if [ -z "$1" ]
then echo "Usage:\n $0 file.to.convert"
exit 1
fi

ffmpeg -i "$1" -c:v libx264 -c:a aac -strict -2 -b:v 3M -s 1280x720 -b:a 128k -y "${1}-converted.mp4"

cp "${1}-converted.mp4 ~/Desktop/

